### ISSUE TITLE
Code review artifacts not available in Maven repo

### ISSUE THREAD

**Issue by ChickyD** [fastconnect/tibco-codereview#1]
Hi team,

i cannot download code review artifacts from the maven central repository. I could not find them in the maven repository.

Downloading: https://repo.maven.apache.org/maven2/fr/fastconnect/factory/tibco/bw/codereview/code-review-rules-basic/2.0.0/code-review-rules-basic-2.0.0-bw.jar
Downloading: https://repo.maven.apache.org/maven2/fr/fastconnect/factory/tibco/bw/codereview/code-review-resources/2.0.0/code-review-resources-2.0.0-display.jar
[DEBUG] Writing tracking file C:\Users\Ashish.m2\repository\fr\fastconnect\factory\tibco\bw\codereview\code-review-resources\2.0.0\code-review-resources-2.0.0-display.jar.lastUpdated
[DEBUG] Writing tracking file C:\Users\Ashish.m2\repository\fr\fastconnect\factory\tibco\bw\codereview\code-review-rules-basic\2.0.0\code-review-rules-basic-2.0.0-bw.jar.lastUpdated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.880 s
[INFO] Finished at: 2016-10-02T11:17:41+05:30
[INFO] Final Memory: 18M/105M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project simpleproject: Could not resolve dependencies for project com.company.project:simpleproject:bw-ear:1.0.0: The following artifacts could not be resolved: fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0, fr.fastconnect.factory.tibco.bw.codereview:code-review-rules-basic:jar:bw:2.0.0: Could not find artifact fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project simpleproject: Could not resolve dependencies for project com.company.project:simpleproject:bw-ear:1.0.0: The following artifacts could not be resolved: fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0, fr.fastconnect.factory.tibco.bw.codereview:code-review-rules-basic:jar:bw:2.0.0: Could not find artifact fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0 in central (https://repo.maven.apache.org/maven2)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project com.company.project:simpleproject:bw-ear:1.0.0: The following artifacts could not be resolved: fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0, fr.fastconnect.factory.tibco.bw.codereview:code-review-rules-basic:jar:bw:2.0.0: Could not find artifact fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0 in central (https://repo.maven.apache.org/maven2)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0, fr.fastconnect.factory.tibco.bw.codereview:code-review-rules-basic:jar:bw:2.0.0: Could not find artifact fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0 in central (https://repo.maven.apache.org/maven2)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0, fr.fastconnect.factory.tibco.bw.codereview:code-review-rules-basic:jar:bw:2.0.0: Could not find artifact fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0 in central (https://repo.maven.apache.org/maven2)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
        ... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact fr.fastconnect.factory.tibco.bw.codereview:code-review-resources:jar:display:2.0.0 in central (https://repo.maven.apache.org/maven2)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Mentioned below is the project pom.

<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fr.fastconnect.factory.tibco</groupId>
    <artifactId>fc-tibco-factory</artifactId>
    <version>2.4.1</version>
  </parent>
  <groupId>com.company.project</groupId>
  <artifactId>simpleproject</artifactId>
  <version>1.0.0</version>
  <packaging>bw-ear</packaging>
  <name>simpleproject project</name>
  <properties>
    <bw.project.name>simpleproject</bw.project.name>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.company.project</groupId>
      <artifactId>simpleprojectlib</artifactId>
      <version>1.0.0</version>
      <type>projlib</type>
    </dependency>
  <dependency>
    <groupId>fr.fastconnect.factory.tibco.bw.codereview</groupId>
    <artifactId>code-review-resources</artifactId>
    <version>2.0.0</version>
    <classifier>display</classifier>
    <scope>test</scope>
  </dependency>
  <dependency>
    <groupId>fr.fastconnect.factory.tibco.bw.codereview</groupId>
    <artifactId>code-review-rules-basic</artifactId>
    <version>2.0.0</version>
    <classifier>bw</classifier>
    <scope>test</scope>
  </dependency>

  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>fr.fastconnect.factory.tibco.bw.maven</groupId>
        <artifactId>bw-maven-plugin</artifactId>
        <version>${bw.maven.plugin.version}</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
</project>

Please let me know if you need any further information.

**Comment by pvrhijn** [comment]
Hi,

As far as I can tell, there is not yet an artifact of the codereview project available in any maven repository.
I used the source from Git of the review project to publish a maven artifact in our company maven repository.

You could try to generate the artifacts from source and install them in your local maven repo first.

**Comment by ChickyD** [comment]
Thank you.
